const girlfriendName="Ladoooo";const yourName="Your Name";document.title=`For ${girlfriendName} ❤️`;document.getElementById("yourName").textContent=yourName;
let current="s0";function show(id){document.getElementById(current).classList.remove("active");setTimeout(()=>document.getElementById(id).classList.add("active"),20);current=id;burst(12);scrollTo(0,0)}
document.querySelectorAll("[data-next]").forEach(b=>b.onclick=()=>show(b.dataset.next));
document.getElementById("yes").onclick=()=>show("s2");
let n=0;document.getElementById("no").onclick=()=>{n++;document.getElementById("noMsg").textContent=["Are you sure? 👀","That button is shy 😂","Try again 😌","You mean YES ❤️"][Math.min(n-1,3)];if(n>1)document.getElementById("no").style.transform=`translate(${Math.random()*140-70}px,${Math.random()*80-40}px)`;if(n>=5){document.getElementById("no").textContent="YES ❤️";document.getElementById("no").onclick=()=>show("s2")}};
document.querySelectorAll(".pic").forEach(p=>p.onclick=()=>{document.getElementById("bigPhoto").src=p.dataset.img;document.getElementById("caption").textContent=p.dataset.cap;document.getElementById("photoModal").classList.remove("hidden")});
document.querySelector("#photoModal .close").onclick=()=>document.getElementById("photoModal").classList.add("hidden");
function openLetter(){document.getElementById("envelope").classList.add("open");burst(15);setTimeout(()=>show("s5"),800)}document.getElementById("envelope").onclick=openLetter;document.getElementById("openLetter").onclick=openLetter;
document.querySelectorAll(".gift").forEach(g=>g.onclick=()=>{document.getElementById("giftText").textContent=g.dataset.text;document.getElementById("giftModal").classList.remove("hidden");burst(12)});
document.querySelector("#giftModal .close").onclick=()=>document.getElementById("giftModal").classList.add("hidden");
const qs=[["What should we make more of?",["Memories ❤️","Arguments","Homework","Nothing"],0],["Who deserves the biggest birthday hug?",["Me","You ♥","Nobody","The cat"],1],["What do I love most about you?",["Your smile","Your heart","Your personality","All of you"],3],["What should our next chapter have?",["Adventures","Laughter","Memories","All of these"],3],["Ready for the final surprise?",["YES ❤️","Absolutely","Of course","ALL"],3]];let qi=0,score=0;
function quiz(){document.getElementById("qnum").textContent=`${qi+1} / ${qs.length}`;document.getElementById("score").textContent=`${score} ❤️`;document.getElementById("question").textContent=qs[qi][0];let box=document.getElementById("answers");box.innerHTML="";document.getElementById("feedback").textContent="";qs[qi][1].forEach((x,i)=>{let b=document.createElement("button");b.className="answer";b.textContent=x;b.onclick=()=>answer(i,b);box.appendChild(b)})}
function answer(i,b){let c=qs[qi][2];document.querySelectorAll(".answer").forEach(x=>x.disabled=true);if(i===c){b.classList.add("good");score++;document.getElementById("feedback").textContent="Correct! ❤️"}else{b.classList.add("bad");document.querySelectorAll(".answer")[c].classList.add("good");document.getElementById("feedback").textContent="Close! 😄"}setTimeout(()=>{qi++;if(qi<qs.length)quiz();else{document.getElementById("question").textContent=`${score}/${qs.length} — pretty good!`;document.getElementById("answers").innerHTML='<button class="primary" id="quizNext">Continue 🎵</button>';document.getElementById("quizNext").onclick=()=>show("s8")}},750)}quiz();
const audio=document.getElementById("audio"),play=document.getElementById("play"),record=document.getElementById("record");play.onclick=()=>{if(audio.paused){audio.play().then(()=>{play.textContent="❚❚ Pause";record.classList.add("spin")}).catch(()=>alert("Add your song as music/song.mp3"))}else{audio.pause();play.textContent="▶ Play our song";record.classList.remove("spin")}};
document.getElementById("final").onclick=()=>{document.getElementById("reveal").classList.remove("hidden");document.getElementById("final").textContent="Happy Birthday! ❤️";confetti(180);burst(40)};
function heart(){let e=document.createElement("span");e.className="heart";e.textContent=["♥","♡","💕","💗","✨"][Math.floor(Math.random()*5)];e.style.left=Math.random()*100+"vw";e.style.fontSize=18+Math.random()*28+"px";document.body.appendChild(e);setTimeout(()=>e.remove(),6000)}function burst(n){for(let i=0;i<n;i++)setTimeout(heart,i*35)}function confetti(n){for(let i=0;i<n;i++){let e=document.createElement("span");e.className="conf";e.style.left=Math.random()*100+"vw";e.style.background=["#f08aaa","#f5d06d","#a8d8e8","#bca4df","#9dd4b0"][Math.floor(Math.random()*5)];e.style.animationDelay=Math.random()*1.3+"s";document.body.appendChild(e);setTimeout(()=>e.remove(),6000)}}setInterval(()=>{if(current!=="s0")heart()},1400);